//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * We assume that the input minijava program is type-checked
 */

class SymbolTable
{
   HashMap<String,ClassTable> cList;
   int scope_flag ;
   ClassTable curr_class;
   FunctionTable curr_fn;
   HashMap<String,Boolean> flagMap;
   int temp_cnt=100;
   int label_cnt=0;

   SymbolTable(){
      cList = new HashMap<String,ClassTable>();
      flagMap = new HashMap<String,Boolean>();
      scope_flag=0;
      curr_class=null;
      curr_fn=null;
   }

   String getNewTemp(){
      return Integer.toString(temp_cnt++);
   }

   String getNewLabel(){
      return "L" + Integer.toString(label_cnt++);
   }

   void addClass(String cname){
      ClassTable obj = new ClassTable(cname);
      flagMap.put(cname,false);
      cList.put(cname, obj);
   }

   void addClass(String cname, String pname)
   {
      ClassTable obj = new ClassTable(cname,pname);
      flagMap.put(cname,false);
      cList.put(cname,obj);
   }

   void addFunction(String rtype, String fname){
      curr_class.addFunction(rtype,fname);
   }

   void setCurrClass(String cname){
      scope_flag = 1;
      curr_class = cList.get(cname);
   }

   void setCurrFn(String fname){
      scope_flag = 2;
      curr_fn = curr_class.cFnList.get(fname);
   }

   void unsetCurrFn(){
      scope_flag=1;
      curr_fn=null;
   }
   void unsetCurrClass(){
      scope_flag=0;
      curr_class=null;
   }

   void insertField(String type,String id){
      switch(scope_flag){
         case 1:
            curr_class.insertField(type,id);
         break;
         case 2:
            curr_fn.insertField(type,id);
         break;
         default:
         //Do nothing
      }
   }

   void addFunctionArgument(String type, String id){
      curr_fn.addFunctionArgument(type,id);
   }

   ArrayList<String> recAppendVTable(String cname)
   {  
      ClassTable c_obj = cList.get(cname);

      if(c_obj.parentName.equals("")){
         return c_obj.getVtable();
      }
      else if(flagMap.get(cname)==true){
         return c_obj.getVtable();
      }
      else{
         ArrayList<String> vtab_parent = recAppendVTable(c_obj.parentName);
         ArrayList<String> vtab_child = c_obj.getVtable();
         
         for(int i=0;i<vtab_child.size();++i){
            boolean flag=false;//flag to check overriding
            String str1 = vtab_child.get(i);
            str1 = str1.substring(str1.indexOf('_') + 1);
            for(int j=0;j<vtab_parent.size();++j){
               String str2 = vtab_parent.get(i);
               str2 = str2.substring(str2.indexOf('_') + 1);
               if(str1.equals(str2)){
                  //replace string and break
                  vtab_parent.set(j,vtab_child.get(i));
                  flag=true;
                  break;
               }
            }   
            if(!flag){
               //not overriding-append to the end of the list
               vtab_parent.add(vtab_child.get(i));
            }
         }

         return vtab_parent;
      }
      
   }

   ArrayList<String> recAppendFieldTable(String cname,int choice){
      
      ClassTable c_obj = cList.get(cname);

      if(c_obj.parentName.equals("")){
         if(choice==1)return c_obj.getFieldTable(1);
         else return c_obj.getFieldTable(2);
      }
      else if(flagMap.get(cname)==true){
         if(choice==1)return c_obj.getFieldTable(1);
         else return c_obj.getFieldTable(2);
      }
      else{
         ArrayList<String> field_parent = recAppendFieldTable(c_obj.parentName,choice);
         ArrayList<String> field_child = c_obj.getFieldTable(choice);

         for(int i=0;i<field_child.size();++i){
            field_parent.add(field_child.get(i));            
         }

         return field_parent;
      }
   }

   void resetFlags(){
      Iterator it = flagMap.entrySet().iterator();
      while(it.hasNext()){
         Map.Entry<String, Boolean> pair = (Map.Entry<String,Boolean>) it.next();
         flagMap.replace(pair.getKey(),true,false);
      }
   }

   void appendTables(){
      //Recursively append tables of all the classes
      Iterator it = cList.entrySet().iterator();

      //Append vtables
      while (it.hasNext())
      {
         Map.Entry<String, ClassTable> pair = (Map.Entry<String,ClassTable>) it.next();
         ArrayList<String> vtable_new = this.recAppendVTable(pair.getKey());
         pair.getValue().putVTable(vtable_new);
         flagMap.replace(pair.getKey(),false,true);
         /* System.out.println("~~~~~~~" + pair.getKey() + "~~~~~~~~~~");
         for(int i=0;i<pair.getValue().vtable.size();++i){
            System.out.println(pair.getValue().vtable.get(i));
         }  */
      }
      resetFlags();
      it = cList.entrySet().iterator();
      //Append global fields
      while(it.hasNext()){
         Map.Entry<String, ClassTable> pair = (Map.Entry<String,ClassTable>) it.next();
         ArrayList<String> cfield_new = this.recAppendFieldTable(pair.getKey(),1);
         ArrayList<String> cfieldType_new = this.recAppendFieldTable(pair.getKey(),2);
         
         pair.getValue().putField(cfieldType_new,cfield_new);
         flagMap.replace(pair.getKey(),false,true);
      }
      resetFlags();
   }

   String getReturnType(String cname, String fname){
      //We know for sure the function is present in given class or ancestor
      ClassTable c_obj  = cList.get(cname);
      if(c_obj.cFnList.containsKey(fname)){
         return c_obj.cFnList.get(fname).rtype;
      }
      else{
         return getReturnType(c_obj.parentName, fname);
      }
   }
}

class ClassTable
{

   ArrayList<String> vtable;
   HashMap<String,FunctionTable> cFnList;
   ArrayList<String> cField;
   ArrayList<String> cFieldType;
   String className;
   String parentName;
   int vtable_size;
   int classtable_size;

   ClassTable(){
      className = "";
      parentName = "";
   }

   ClassTable(String cname){
      className = cname;
      parentName = "";
      vtable = new ArrayList<String>();
      cFnList = new HashMap<String,FunctionTable>();
      cField = new ArrayList<String>();
      cFieldType = new ArrayList<String>();
      vtable_size = classtable_size = 0;
   }

   ClassTable(String cname,String pname){
      className = cname;
      parentName = pname;
      vtable = new ArrayList<String>();
      cFnList = new HashMap<String,FunctionTable>();
      cField = new ArrayList<String>();
      cFieldType = new ArrayList<String>();
      vtable_size = classtable_size = 0;

   }

   ArrayList<String> getVtable(){
      //return a deep copy of vtable
      ArrayList<String> vtable_cp = new ArrayList<String>();
      for(int i=0;i<this.vtable.size();++i){
         vtable_cp.add(this.vtable.get(i));
      }
      return vtable_cp;
   }

   ArrayList<String> getFieldTable(int choice){
      //return a deep copy of the tables
      if(choice==1){
         ArrayList<String> field_cp = new ArrayList<String>();
         for(int i=0;i<this.cField.size();++i){
            field_cp.add(this.cField.get(i));
         }
         return field_cp;
      }
      else {
         ArrayList<String> field_cp = new ArrayList<String>();
         for(int i=0;i<this.cFieldType.size();++i){
            field_cp.add(this.cFieldType.get(i));
         }
         return field_cp;
      }
   }
   //Add superclass fields-modify classtable_size
   void putField(ArrayList<String> type,ArrayList<String> val){
      this.cField = new ArrayList<String>();
      this.cFieldType = new ArrayList<String>();
      for(int i=0;i<val.size();++i){
         this.cField.add(val.get(i));
      }
      for(int i=0;i<type.size();++i){
         this.cFieldType.add(type.get(i));
      }
      this.classtable_size = 1 + type.size();
   }

   //Add superclass functions-modify vtable_size
   void putVTable(ArrayList<String> vtable){
      this.vtable = new ArrayList<String>();
      for(int i=0;i<vtable.size();++i){
         this.vtable.add(vtable.get(i));
      }
      this.vtable_size = vtable.size();
   }

   void insertField(String type,String id){
      cFieldType.add(type);
      cField.add(className + "_" + id);
   }

   void addFunction(String rtype, String fname){
      FunctionTable obj = new FunctionTable(fname,rtype,className);
      cFnList.put(fname,obj);
      vtable.add(className+"_" +fname);
   }

   int getFieldIndexOffset(String id){
      int ind = -1;
      for(int i=cField.size()-1;i>=0;--i){
         String str = cField.get(i);
         str = str.substring(str.indexOf('_')+1);
         if(id.equals(str)){
            ind = i;
            break;
         }
      }
      //System.out.println("~~~~~~~~~~offset is ~~~~~~~~```" + ind);
      return ind;
   }

   int getVTableOffset(String fname){
      int ind=-1;
      for(int i=0;i<vtable.size();++i){
         String str = vtable.get(i);
         str = str.substring(str.indexOf('_')+1);
         if(str.equals(fname)){
            ind = i;
            break;
         }
      }
      return ind;
   }

   String getType(String id){

      int ind = 1;
      for(int i=cField.size()-1;i>=0;--i){
         String str = cField.get(i);
         str = str.substring(str.indexOf('_')+1);
         if(id.equals(str)){
            ind = i;
            break;
         }
      }

      return cFieldType.get(ind);
   }

   String getVTableClassAt(int offset){
      
      //int ind = getVTableOffset(fname);
      String str = vtable.get(offset);
      return str.substring(0,str.indexOf('_')+1);
   }
}

class FunctionTable
{
   ArrayList<String> fArg;
   ArrayList<String> fArgType;
   ArrayList<String> fField;
   ArrayList<String> fFieldType;
   String className;
   String functionName;
   String rtype;
   int N_args;
   int N_fields;

   FunctionTable(){}

   FunctionTable(String fname, String rtype,String className){
      functionName = fname;
      this.rtype = rtype;
      this.className = className;
      fArg = new ArrayList<String>();
      fArgType = new ArrayList<String>();
      fField = new ArrayList<String>();
      fFieldType = new ArrayList<String>();
      fArg.add("_this");
      fArgType.add(className);
      N_args=1;
      N_fields=0;
   }

   void insertField(String type,String id){
      fField.add(id);
      fFieldType.add(type);
      N_fields++;
   }

   void addFunctionArgument(String type,String id){
      fArg.add(id);
      fArgType.add(type);
      N_args++;
   }

   int getNumberArgs(){
      return fArg.size();
   }

   boolean checkField(String id){
      return (fArg.contains(id) || fField.contains(id));
   }

   int getFieldIndexTemp(String id){
      //returns the index of element containing id
      //always returns a value
      boolean flag = false;
      int ans = 0;

      for(int i=0;i<N_args;++i){
         if(fArg.get(i).equals(id)){
            flag=true;
            ans = i;
            break;
         }
      }
      if(flag){
         return ans;
      }else{

         for(int i=0;i<N_fields;++i){
            if(fField.get(i).equals(id)){
               flag=true;
               ans = i + N_args;
               break;
            }
         }

         return ans;
      }
   }

   String getType(String id){
      
      boolean flag = false;
      int ind = 0;

      for(int i=0;i<N_args;++i){
         if(fArg.get(i).equals(id)){
            flag=true;
            ind = i;
            break;
         }
      }
      if(flag){
         return fArgType.get(ind);
      }else{

         for(int i=0;i<N_fields;++i){
            if(fField.get(i).equals(id)){
               flag=true;
               ind = i;
               break;
            }
         }

         return fFieldType.get(ind);
      }
   }

}

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

public class GJDepthFirst<R,A> implements GJVisitor<R,A> {

   //Initialize the symbol table
   SymbolTable T = new SymbolTable();

   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   //Return the name of the identifier
   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }

   //
   // User-generated visitor methods below
   //
   
   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */

   public R visit(Goal n, A argu) {
      
      R _ret=null;

      //Build symbol tables
      n.f0.accept(this, (A)"one");
      n.f1.accept(this, (A)"one");
      n.f2.accept(this, (A)"one");
      
      //Append tables of super classes to derived classes-ensure same indexing
      T.appendTables();

      //Do IR generation of code
      n.f0.accept(this,(A)"two");
      n.f1.accept(this, (A)"two");
      n.f2.accept(this, (A)"two");

      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;String id = "";
      n.f0.accept(this, argu);
      id = (String)n.f1.accept(this, argu);
      T.addClass(id);
      T.setCurrClass(id);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      if(argu.toString().equals("two"))System.out.println("MAIN");
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);     
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      T.unsetCurrClass();
      if(argu.toString().equals("two"))System.out.println("\nEND");
      
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      String cname = "";
      n.f0.accept(this, argu);
      cname = n.f1.accept(this, argu).toString();
      
      if(argu.toString().equals("one"))
         T.addClass(cname);
      
      T.setCurrClass(cname);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      
      T.unsetCurrClass();
      
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;String cname = "";String pname = "";
      n.f0.accept(this, argu);
      cname = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      pname = (String)n.f3.accept(this, argu);
      
      if(argu.toString().equals("one"))
      {
         T.addClass(cname,pname);
      }

      T.setCurrClass(cname);

      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      
      T.unsetCurrClass();
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;String type="";String id = "";
      type = (String)n.f0.accept(this, argu);
      id = (String)n.f1.accept(this, argu);

      if(argu.toString().equals("one"))
      {
         T.insertField(type,id);
      }

      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;String rtype="";String fname = "";
      n.f0.accept(this, argu);
      rtype = (String)n.f1.accept(this, argu);
      fname = (String)n.f2.accept(this, argu);
      
      if(argu.toString().equals("one")){
         T.addFunction(rtype,fname);
      }

      T.setCurrFn(fname);
      
      if(argu.toString().equals("two")){
         //Print function name
         System.out.print("\n" + T.curr_fn.className + "_" + T.curr_fn.functionName + " ");
      }

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      
      if(argu.toString().equals("two")){
         //Print number of arguments and begin function      
         System.out.print("[" + T.curr_fn.getNumberArgs() + "]\n");
         System.out.print("BEGIN\n");
      }
      
      //Accept the fn local variables and the statements
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);

      //Process return statement
      n.f9.accept(this, argu);
      
      if(argu.toString().equals("two")){
         //Print number of arguments      
         System.out.print("\nRETURN ");
      }

      //print the expresssion
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      
      if(argu.toString().equals("two")){
         //Print end statement     
         System.out.print("\nEND\n");
      }
      n.f12.accept(this, argu);
      //Remove the current function from the scope 
      T.unsetCurrFn();

      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;String type = "";String id = "";
      
      type = (String)n.f0.accept(this, argu);
      id = (String)n.f1.accept(this, argu);
      
      if(((String)argu).equals("one"))
      {
         T.addFunctionArgument(type,id);
      }

      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      _ret = (R)("int[]");
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;String id = "";

      id = (String)n.f0.accept(this, argu); 
      n.f1.accept(this, argu);
      if(argu.toString().equals("two")){
         //check if variable is in the current fn field
         if(T.curr_fn.checkField(id)){

            System.out.print("\nMOVE TEMP " +  T.curr_fn.getFieldIndexTemp(id) + " ");
         
         }else{
            //it is in the class field
            int offset = T.curr_class.getFieldIndexOffset(id);
            System.out.print("\nHSTORE TEMP 0 " + (offset+1)*4 + " ");
         }
         
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;String id = "";
      String tmp_arr =T.getNewTemp();
      String tmp_ex1 = T.getNewTemp();
      String tmp_ex2 = T.getNewTemp();
      String tmp_offset = T.getNewTemp();

      id = (String)n.f0.accept(this, argu);
      if(argu.toString().equals("two")){
         //Store the correct array in tmp1
         System.out.print("\nMOVE TEMP " + tmp_arr + " ");
         
         if(T.curr_fn.checkField(id)){
            System.out.print(" TEMP " + T.curr_fn.getFieldIndexTemp(id) + " ");
         }
         else{
            String tmp_og = T.getNewTemp();
            //its in the class list-get the appropriate entry and return
            System.out.print("\nBEGIN");
            int offset = T.curr_class.getFieldIndexOffset(id);
            System.out.print("\nHLOAD TEMP " + tmp_og + " TEMP 0 " + 4*(offset+1) + " ");
            System.out.print("\nRETURN TEMP " + tmp_og);
            System.out.print("\nEND");
         }
         System.out.print("\nMOVE TEMP "+ tmp_ex1 + " ");
      }
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\nMOVE TEMP " + tmp_ex2 + " ");
      }
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\nHSTORE PLUS TEMP " + tmp_arr + " ");
         System.out.print(" TIMES 4 TEMP " + tmp_ex1+ " 4 " );
         System.out.print(" TEMP "+ tmp_ex2 + " ");
         System.out.print("\n");
      }
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      String tmp1 = T.getNewTemp();
      String l1 = T.getNewLabel();

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      if(argu.toString().equals("two")){
         System.out.print("\nMOVE TEMP " + tmp1 + " ");
      }
      
      n.f2.accept(this,argu);
      n.f3.accept(this, argu);
      
      if(argu.toString().equals("two")){
         System.out.print("\nCJUMP TEMP " + tmp1 + " " + l1  + " ");
      }
      
      n.f4.accept(this, argu);
      
      if(argu.toString().equals("two")){
         System.out.print("\n" + l1  + "   NOOP ");
      }
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      String tmp1 = T.getNewTemp();
      String l1 = T.getNewLabel();
      String l2 = T.getNewLabel();

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      
      if(argu.toString().equals("two")){
         System.out.print("\nMOVE TEMP " + tmp1 + " ");
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      
      if(argu.toString().equals("two")){
         System.out.print("\nCJUMP TEMP " + tmp1 + " " + l1  + " ");
      }
      n.f4.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\nJUMP " + l2  + " ");
      }
      n.f5.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\n" + l1  + "\t");
      }
      //accept else part
      n.f6.accept(this, argu);
      //goto l2 if nothing
      if(argu.toString().equals("two")){
         System.out.print("\n" + l2  + "    NOOP \n");
      }
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      String l1 = T.getNewLabel();
      String l2 = T.getNewLabel();

      if(argu.toString().equals("two")){
         System.out.print("\n" + l1 + " NOOP ");
         System.out.print("\nCJUMP  ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\t" + l2 + " " );
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("\nJUMP " + l1+" ");
         System.out.print("\n" + l2  +  " NOOP " );
      }

      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two"))System.out.print("PRINT ");
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      //call Expression
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two")){
         System.out.print("TIMES ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String temp = "";String l1 = ""; String l2 = "";
      l1 = T.getNewLabel();
      l2 = T.getNewLabel();

      if(argu.toString().equals("two")){
         System.out.print("\nBEGIN\n");
         temp = T.getNewTemp();
         System.out.print("MOVE TEMP " + temp + " ");
      }
      n.f0.accept(this, argu);
      
      if(argu.toString().equals("two")){
         System.out.print("\nCJUMP TEMP " + temp + " " + l1);
         System.out.print("\nJUMP " + l2 + " ");
         System.out.print("\n" + l1 + " MOVE TEMP " + temp + " ");
      }

      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      if(argu.toString().equals("two")){
         System.out.print("\n" + l2 + " NOOP  ");
         System.out.print("\nRETURN TEMP " + temp + " ");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two")){
         System.out.print(" LE ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;

      if(argu.toString().equals("two")){
         System.out.print(" NE ");
      }

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two"))System.out.print(" PLUS ");
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      if(argu.toString().equals("two"))System.out.print("\n");
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two"))System.out.print(" MINUS ");
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two")){
         System.out.print(" TIMES ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      /* if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType(" in TimesExpression");
         }
         _ret = (R)("int");
      } */
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two")){
         System.out.print(" DIV ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      /* if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType(" in DivExpression");
         }
         _ret = (R)("int");
      } */
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String tmp1 = T.getNewTemp();
      String tmp2 = T.getNewTemp();
      String tmp3 = T.getNewTemp();

      if(argu.toString().equals("two")){
         System.out.print("\nBEGIN");
         System.out.print("\nMOVE TEMP " + tmp1 + " ");
      }
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      //get offset
      if(argu.toString().equals("two")){
         //System.out.print("\nBEGIN");
         System.out.print("\nMOVE TEMP " + tmp2 + " ");
      }
      n.f2.accept(this, argu);

      //return the element at tmp1+tmp2
      if(argu.toString().equals("two")){

         System.out.print("\nHLOAD TEMP " + tmp3 + " PLUS TEMP " + tmp1 + " PLUS 4 TIMES 4 TEMP " + tmp2 + " 0 ");
         System.out.print("\nRETURN TEMP " + tmp3 + " ");
         System.out.print("\nEND");
      }
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String tmp1 = T.getNewTemp();
      String tmp2 = T.getNewTemp();
      if(argu.toString().equals("two")){
         System.out.print("\nBEGIN");
         System.out.print("\nMOVE TEMP " + tmp1 + " ");
      }
      n.f0.accept(this, argu);
      //Just print the first element of tmp1 into temp2
      
      if(argu.toString().equals("two")){
         System.out.print("\nHLOAD TEMP " + tmp2 + " TEMP " + tmp1 + " 0 ");
         System.out.print("\nRETURN TEMP " + tmp2);
         System.out.print("\nEND");
      }

      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {

      R _ret=null;
      String cname = "";
      String fname = "";
      String return_type = "";
      String tmp_obj = T.getNewTemp();
      String tmp_vt = T.getNewTemp();
      String tmp_offset = T.getNewTemp();
      
      if(argu.toString().equals("two")){
         System.out.print("\nCALL");
         System.out.print("\n\tBEGIN");
         System.out.print("\nMOVE TEMP " + tmp_obj + " " );
      }
      //if class name is this, then im printing TEMP 0 in ThisExpression else print identifier in primary expr
      cname = (String)n.f0.accept(this, argu);                                
      n.f1.accept(this, argu);
      fname = (String)n.f2.accept(this, argu);
      
      if(argu.toString().equals("two")){
         //get the offset in the vtable where fname is present
         int offset = 0;
         //System.out.println("\n~~~~~~~~curr_class is::" + T.curr_class.className);
         //System.out.println("~~~~~~~~~~~`Function name::fname = "+ fname);
         //System.out.println("Cname is =" + cname);
         //if(fname.equals("GetKey"))System.out.println("In function " + T.curr_fn.functionName);
         //Get the returntype of the function

         if(cname.equals("this")){

            offset = T.curr_class.getVTableOffset(fname);
            // System.out.println("~~~~~~~~~~The vtable offset for this is=" + offset);
            _ret = (R)T.getReturnType(T.curr_class.className, fname);
         }else{
            //System.out.println("cname is = " + cname);
            offset = T.cList.get(cname).getVTableOffset(fname);
            _ret = (R)T.getReturnType(cname,fname);
         }
         System.out.print("\nHLOAD TEMP " + tmp_vt + " TEMP " + tmp_obj + " 0 ");
         System.out.print("\nHLOAD TEMP " + tmp_offset + " TEMP " + tmp_vt + " " + offset*4+ " ");
         System.out.print("\nRETURN TEMP " + tmp_offset+ " ");
         System.out.print("\nEND");
      }

      n.f3.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print("( TEMP " + tmp_obj +" ");
      }
      n.f4.accept(this, argu);

      n.f5.accept(this, argu);
      if(argu.toString().equals("two"))
         System.out.print(" ) ");
      
      //Return function returntype 
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret = (R)"";
      String farg = (String)n.f0.accept(this, argu);
      if(((String)argu).equals("two")) 
      {
          if(n.f1.present())
          {
              for(int i=0;i<n.f1.size();++i)
              {
                  farg +=(String)n.f1.elementAt(i).accept(this, argu);
              }
          }  
          _ret = (R)farg;
      } 
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=(R)"";
      String farg = (String)n.f0.accept(this, argu);
      farg = farg + (String)n.f1.accept(this, argu);
      if(((String)argu).equals("two"))_ret = (R)farg;
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      if(argu.toString().equals("two")){
         if(n.f0.which == 3){
            //Identifier->need to print it
            String id = (String)_ret;
            if(T.curr_fn.checkField(id)){
               System.out.print("\nTEMP " +  T.curr_fn.getFieldIndexTemp(id) + " ");
               _ret = (R)T.curr_fn.getType(id);
            }else{
               //it is in the class field
               System.out.print("\nBEGIN");
               String tmp = T.getNewTemp();
               int offset = T.curr_class.getFieldIndexOffset(id);
               _ret = (R)T.curr_class.getType(id);
               System.out.print("\nHLOAD TEMP "+ tmp +" TEMP 0 " + (offset+1)*4 + " ") ;
               System.out.print("\nRETURN TEMP " + tmp);
               System.out.print("\nEND");
            }
         }
         
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=(R)"int";
      String val = "";
      val = (String)n.f0.accept(this, argu);
      if(argu.toString().equals("two")){
         System.out.print(" " + val + " ");
      }
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=(R)"boolean";
      n.f0.accept(this, argu);
      if(argu.toString().equals("two"))System.out.print(" 1 ");
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=(R)"boolean";
      n.f0.accept(this, argu);
      if(argu.toString().equals("two"))System.out.print(" 0 ");

      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;   
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)T.curr_class.className;
      if(argu.toString().equals("two")){
         //Inside a function
         if(T.scope_flag==2){
            System.out.print("\nTEMP 0");
         }
         _ret = (R)"this";
      } 
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      
      String tmp1 = "";String tmp2 = "";String tmp3 = "";String tmp4 = "";
      tmp1 = T.getNewTemp();
      tmp2 = T.getNewTemp();
      tmp3 = T.getNewTemp();

      String l1 = T.getNewLabel();
      String l2 = T.getNewLabel();

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if(argu.toString().equals("two")){
         //tmp1 contains the size of the array
         System.out.print("\nBEGIN"); 
         System.out.print("\nMOVE TEMP " + tmp1 + " " );
     
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      if(argu.toString().equals("two")){
         //size =  tmp1+1 to array in tmp2
         System.out.print("\nMOVE TEMP " + tmp2 + " HALLOCATE  TIMES  PLUS TEMP " + tmp1 +  "  1  4 ");
         //make tmp3 as an iterator
         System.out.print("\nMOVE TEMP " +  tmp3 + " 4 ");
         System.out.print("\n"+l1 + "\tCJUMP  LE TEMP " + tmp3+" MINUS TIMES  PLUS TEMP "+tmp1+"  1  4 1 " + l2 + " "); 
         System.out.print("\nHSTORE  PLUS TEMP "+ tmp2 + " TEMP " + tmp3+  "  0  0 "); 
         System.out.print("\nMOVE TEMP " + tmp3 + "  PLUS TEMP " + tmp3 + " 4 "); 
         System.out.print("\nJUMP " + l1 + " " );
         //store the length as is in arr[0]
         System.out.print("\n" + l2 + " 	HSTORE TEMP " + tmp2 + "  0 TEMP " + tmp1 +"  "); 
         System.out.print("\nRETURN "); 
         System.out.print("\nTEMP " + tmp2 + " "); 
         System.out.print("\nEND");  
      }
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      String class_name = "";
      n.f0.accept(this, argu);
      class_name = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      if(argu.toString().equals("two")){
         //get the class to be initialized
         ClassTable c_obj = T.cList.get(class_name);

         System.out.print("\nBEGIN ");
         //Initialize vtable
         String vtable_ptr = T.getNewTemp();
         //Initialize the classtable pointer
         String classtab_ptr = T.getNewTemp();
         
         System.out.print("\nMOVE TEMP " + vtable_ptr + " HALLOCATE " + (4 * c_obj.vtable_size));
         System.out.print("\nMOVE TEMP " + classtab_ptr + " HALLOCATE " + (4 * c_obj.classtable_size));
         
         for(int i=c_obj.vtable_size-1;i>=0;--i){
            System.out.print("\nHSTORE TEMP " + vtable_ptr + " " + (4*i) + " " + c_obj.vtable.get(i)+ " ");
         }

         if(c_obj.classtable_size > 1){
            //use the cjump
            String l0 = T.getNewLabel();
            String l1 = T.getNewLabel();
            String tmp3 = T.getNewTemp();
            System.out.print("\nMOVE TEMP " + tmp3 + " 4");
            System.out.print("\n" + l0 + "\t");
            System.out.print("CJUMP LE TEMP " + tmp3 + " " + (4*c_obj.classtable_size - 1 ) + " " + l1  +" ");
            System.out.print("\nHSTORE PLUS TEMP " + classtab_ptr + " TEMP " + tmp3 + " 0 0 ");
            System.out.print("\nMOVE TEMP " + tmp3 + " PLUS TEMP " + tmp3 + " 4 ");
            System.out.print("\nJUMP " + l0);
            System.out.print("\n" + l1 + "\t");
         }

         System.out.print("\nHSTORE TEMP "+ classtab_ptr + " 0 TEMP " + vtable_ptr);
         System.out.print("\nRETURN TEMP " + classtab_ptr);
         System.out.print("\nEND\n");
      }
      _ret = (R)class_name;
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      if(argu.toString().equals("two"))System.out.print("\nMINUS 1 ");
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret=n.f1.accept(this,argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public R visit(IdentifierList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(IdentifierRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

}
