//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

class ErrorThrower
{
   ErrorThrower()
   {}

   void throwType(String m)
   {
      System.out.println("Type error");
      System.exit(0);
   }

   void throwSymbol(String m)
   {
      System.out.println("Symbol not found");
      System.exit(0);
   }

}
class SymTab
{
   ErrorThrower police = new ErrorThrower();
   HashMap<String,ClassTab> cList;
   
   //0->outside any class
   //1->scope is curr_c
   //2->scope is curr_f
   int scope_flag;

   ClassTab curr_c;
   FunctionTab curr_f;   
 
   SymTab()
   {
      cList = new HashMap<String,ClassTab>();
      scope_flag=0;
      curr_c=null;
      curr_f=null;
   }

   boolean findClass(String cn)
   {
      return cList.containsKey(cn);
   }

   void insertClass(String cn)
   {
      ClassTab objc = new ClassTab(cn);
      if(!cList.containsKey(cn))
      {
         cList.put(cn,objc);
      }
      else
      {
         police.throwType("in insertClass(String)");
      }

   }
 
   void insertClass(String cn, String pt)
   {
      ClassTab objc = new ClassTab(cn,pt);
      if(!cList.containsKey(cn))
      {
         cList.put(cn,objc);
      }
      else
      {
         police.throwType("in insertClass(String,String)");
      }
   }
  
   void insertFunction(String fname,String rtype)
   {
      curr_c.insertFunction(fname, rtype);
   }

   void insertFnArgument(String type, String id)
   {
      curr_f.insertArgument(type, id);
   }

   void setCurrClass(String cn)
   {
      scope_flag=1;
      curr_c = cList.get(cn);
   }

   void setCurrFn(String cf)
   {
      scope_flag=2;
      curr_f = curr_c.fnList.get(cf);
   }

   void unsetCurrFn()
   {
      scope_flag=1;
      curr_f=null;
   }

   void unsetCurrClass()
   {
      scope_flag = 0;
      curr_c=null;
   }

   void insertField(String type,String id)
   {
      switch(scope_flag)
      {
         case 1:
            curr_c.insertCField(type, id);
         break;
         case 2:
            curr_f.insertFField(type, id);
         break;
         default:
            //Will never be encountered
      }
   }

   boolean checkAncestor(String child,String parent)
   {
      if(cList.get(child).classParent.equals(""))return false;
      else if(cList.get(child).classParent.equals(parent))return true;
      else return this.checkAncestor(cList.get(child).classParent, parent);
   }

   boolean verifySignature(String cname, String fname, ArrayList<String> signature)
   {
      ClassTab ct = cList.get(cname);
      if(ct.findFunction(fname))
      {
         if(ct.verifySignature(fname,signature,this))return true;
         else return false;
      }
      else
      {
         //if ct has no parent, then nothing
         //else search in the parent
         if(ct.classParent.equals(""))return false;
         else return this.verifySignature(ct.classParent, fname, signature);        
      }
   }

   //Only called if signature has been verified
   String getReturnType(String cname, String fname, ArrayList<String> signature)
   {
      ClassTab ct = cList.get(cname);
      if(ct.findFunction(fname))return ct.getReturnType(fname, signature);
      else return this.getReturnType(ct.classParent, fname, signature);
   }

   /**
    * Checks and returns if variable var is declared as a field in Class c or its superclass recursively.
    * @param c
    * @param var
    * @return boolean
    */
   boolean findVarInClass(ClassTab c, String var)
   {
      if(c.cfList.containsKey(var))return true;
      else
      {
         if(c.classParent.equals(""))return false;
         else return this.findVarInClass(this.cList.get(c.classParent),var);
      }
   }
   /**
    * Checks and returns whether the given variable can be legally scoped
    * @param var
    * @return boolean
    */
   boolean findVariable(String var)
   {
      //Search if the given variable is in the current scope
      return curr_f.argList.contains(var) || curr_f.ffList.containsKey(var) || this.findVarInClass(curr_c,var);
   }

   String getTypeInClass(ClassTab c, String var)
   {
      if(c.cfList.containsKey(var))return c.cfList.get(var);
      else return this.getTypeInClass(this.cList.get(c.classParent), var);
   }

   String getType(String var)
   {  
      //Invoked only if findVariable returns true
      if(curr_f.argList.contains(var))
      {
         return curr_f.getArgumentType(var);
      }
      else if(curr_f.ffList.containsKey(var))
      {
         return curr_f.ffList.get(var);
      }
      else
      {
         return this.getTypeInClass(curr_c,var);
      }
   }

}

class ClassTab 
{
   ErrorThrower police = new ErrorThrower();
   public HashMap<String,FunctionTab> fnList;
   public HashMap<String,String> cfList;
   String classParent;
   String className;

   ClassTab()
   {
   }

   ClassTab(String name)
   {
      fnList = new HashMap<String, FunctionTab>();
      cfList = new HashMap<String,String>();
      this.className = name;
      this.classParent = "";
   }

   ClassTab(String name,String parent)
   {
      fnList = new HashMap<String, FunctionTab>();
      cfList = new HashMap<String,String>();
      this.className = name;
      this.classParent=parent;
   }

   void insertCField(String type,String id)
   {
      if(!cfList.containsKey(id))
      {
         cfList.put(id,type);
      }
      else
      {
         police.throwType("in insertCField(type,id)");
      }
   }

   void insertFunction(String fname, String rtype)
   {
      FunctionTab objf = new FunctionTab(fname,rtype);

      //No overloading allowed!
      if(!this.fnList.containsKey(fname))
      {
         this.fnList.put(fname,objf);
      }
      else
      {
         this.police.throwType("in insertFunction()");
      }
   }

   boolean findFunction(String fname)
   {
      return fnList.containsKey(fname);
   }

   boolean testSuperClass(String sup, String  chld,SymTab T)
   {
      if(T.cList.get(chld)==null)
      {
         System.out.println(sup);
         System.out.println(chld);
         System.out.println("~~~~~~~~~~~~~~");
         return false;
      }
      if(T.cList.get(chld).classParent.equals(""))return false;
      else if(T.cList.get(chld).classParent.equals(sup))return true;
      else return this.testSuperClass(sup,T.cList.get(chld).classParent,T);
   }
   boolean verifySignature(String fname, ArrayList<String> sgn, SymTab T)
   {
      FunctionTab ft = fnList.get(fname);
      int s1 = sgn.size();
      int s2 = ft.argTypeList.size();
      if(s1!=s2)return false;
      else
      {
         boolean flag = true;
         for(int i=0;i<s1;++i)
         {
            if(!(sgn.get(i).equals(ft.argTypeList.get(i))))
            {
               if(sgn.get(i).equals("int") || sgn.get(i).equals("int[]") || sgn.get(i).equals("boolean"))
               {
                  flag = false;
                  break;
               }
               else
               {
                  //check if the ft.argTypeList.get(i) is a superclass of sgn.get(i) if yes then dont change flag
                  flag = this.testSuperClass(ft.argTypeList.get(i),sgn.get(i),T);
                  if(!flag)break;
               }
            }
         }
         return flag;
      }
   }

   String getReturnType(String fname, ArrayList<String> sgn)
   {
      //Only called if the function has been verified with the given signature
      return this.fnList.get(fname).returnType;
   }

}

class FunctionTab 
{
   ErrorThrower police = new ErrorThrower();

   ArrayList<String> argList;
   ArrayList<String> argTypeList;
   
   HashMap<String,String> ffList;
   String returnType;
   String className;

   FunctionTab()
   {
   }

   FunctionTab(String className,String rtype)
   {
      argList = new ArrayList<String>();
      argTypeList = new ArrayList<String>();
      ffList = new HashMap<String,String>();
      returnType = rtype;
      this.className = className;
   }

   void insertFField(String type,String id)
   {
      if(!this.ffList.containsKey(id))
      {
         this.ffList.put(id,type);
      }
      else
      {
         police.throwType("in insertFField");
      }
   }

   void insertArgument(String type, String id)
   {
      if(!this.argList.contains(id))
      {
         this.argList.add(id);
         this.argTypeList.add(type);
      }
      else
      {
         police.throwType("in insertArgument()");
      }
   }

   String getArgumentType(String val)
   {
      //invoked iif we know val is in argList
      String ret = "";
      for(int i=0;i<argList.size();++i)
      {
         if(val.equals(argList.get(i)))
         {
            ret = argTypeList.get(i);
            break;
         }
      }
      return ret;
   }
}

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

public class GJDepthFirst<R,A> implements GJVisitor<R,A> {

   //initialize the symbol table and error thrower
   SymTab T = new SymTab();
   ErrorThrower police = new ErrorThrower();
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   //Return the name of the identifier
   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }

   //
   // User-generated visitor methods below
   //
   
   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */

   public R visit(Goal n, A argu) {
      R _ret=null;
      //Build symbol table
      n.f0.accept(this, (A)"one");
      n.f1.accept(this, (A)"one");
      n.f2.accept(this, (A)"one");

      //Do type checking
      n.f0.accept(this,(A)"two");
      n.f1.accept(this, (A)"two");
      n.f2.accept(this, (A)"two");

      //Program type checked
      System.out.println("Program type checked successfully");
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      String cn = "";
      n.f0.accept(this, argu);
      cn = (String)n.f1.accept(this, argu);
      if(((String)argu).equals("one"))
      {
         //Insert class into the table
         T.insertClass(cn);
      }
      
      //Set the current context to class before accepting variables
      T.setCurrClass(cn);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      T.unsetCurrClass();
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      String cn = "";
      String pt = "";
      n.f0.accept(this, argu);
      cn = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      pt = (String)n.f3.accept(this, argu);
      if(((String)argu).equals("one"))
      {
         //Insert class and superclass entry into the table
         T.insertClass(cn,pt);
      }
      if(((String)argu).equals("two"))
      {
         //Check if superclass is valid
         if(!T.findClass(pt))
         {
            police.throwSymbol("::"+pt);
         }
      }
      n.f4.accept(this, argu);
      //Set the scope
      T.setCurrClass(cn);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      T.unsetCurrClass();
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      String typ="";
      String id= "";
      typ = (String)n.f0.accept(this, argu);
      id = (String)n.f1.accept(this, argu);
      if(((String)argu).equals("one"))
      {
         T.insertField(typ,id);
      }
      if(argu.toString().equals("two"))
      {
         if(!typ.equals("int") && !typ.equals("int[]") && !typ.equals("boolean"))
         {
            if(!T.findClass(typ))police.throwSymbol("in VarDeclaration of function");
         }
      }
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      String rtype;
      String fname;
      String ret2 = "";
      n.f0.accept(this, argu);
      rtype = (String)n.f1.accept(this, argu);
      fname = (String)n.f2.accept(this, argu);
      
      if(((String)argu).equals("one"))
      {
         T.insertFunction(fname,rtype);
      }

      T.setCurrFn(fname);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      //Accept the fn local variables and the statements
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      
      ret2 = (String)n.f10.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret2.equals(rtype))
         {
            police.throwType("invalid return type in MethodDeclaration" + ret2);
         }
      }
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      //Remove the current function from the scope 
      T.unsetCurrFn();

      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      String type = "";
      String id = "";
      type = (String)n.f0.accept(this, argu);
      id = (String)n.f1.accept(this, argu);
      
      if(((String)argu).equals("one"))
      {
         T.insertFnArgument(type,id);
      }

      if(((String)argu).equals("two"))
      {
         if(!type.equals("int") && !type.equals("int[]") && !type.equals("boolean"))
         {
            if(!T.findClass(type))police.throwSymbol("in FormalParameter of function");
         }
      }
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      String id;
      id = (String)n.f0.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         //Using NodeChoice variable for use
         if(n.f0.which==3)
         {
            //Check if the type is a valid class
            if(!T.findClass(id))police.throwSymbol("::unknown type for "+ id);
         }
      }
      _ret = (R)id;
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      _ret = (R)("int[]");
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String id = "";
      String type = "";
      String ret = "";
      id = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!T.findVariable(id))police.throwSymbol("in AssignmentStatement" + id);
         type = T.getType(id);
         if(ret.equals("this"))ret=T.curr_c.className;
         if(!type.equals(ret))
         {
            police.throwType("in AssignmentStatement");
         }
      }
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String id1,ret1,ret2;
      ret1 = "";ret2 = "";id1 = "";
      id1 = (String)n.f0.accept(this, argu);
      //Must be of type int-search in scopes
      if(argu.toString().equals("two"))
      {
         //Symbol not found
         if(!T.findVariable(id1))police.throwSymbol("in ArrayAssignmentStatement");
         
         //id1 is found
         String type = T.getType(id1);
         if(!type.equals("int[]"))police.throwType("in ArrayAssignmentStatement");
      }
      n.f1.accept(this, argu);
      ret1 = (String)n.f2.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!ret1.equals("int"))police.throwType("in ArrayAssignmentStatement indexing");
      }

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      ret2 = (String)n.f5.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!ret2.equals("int"))police.throwType("In ArrayAssignmentStatement value");
      }
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      String chk = "";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      //check if the return type of f2 is boolean
      chk = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!chk.equals("boolean"))
         {
            police.throwType("ifThenStmt");
         }
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      String chk = "";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      //check if the return type of f2 is boolean
      chk = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!chk.equals("boolean"))
         {
            police.throwType("ifThenElseStmt");
         }
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      String chk = "";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      //check if the return type of f2 is boolean
      chk = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!chk.equals("boolean"))
         {
            police.throwType("While Statement");
         }
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      String chk = "";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      //check if the return type of f2 is integer
      chk = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!chk.equals("int"))
         {
            police.throwType("PrintStatement");
         }
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         
         if(!ret1.equals("boolean") || !ret2.equals("boolean"))
         {
            police.throwType("in andExpression");
         }
         _ret = (R)("boolean");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("boolean") || !ret2.equals("boolean"))
         {
            police.throwType("in orExpression");
         }
         _ret = (R)("boolean");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType("in compareExpression");
         }
         _ret = (R)("boolean");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals(ret2))
         {
            //If any are primitive(int,bool or int []) then throw error and exit
            if(ret1.equals("int")||ret1.equals("boolean")||ret1.equals("int[]"))
               police.throwType("unmatched type in neqExpression for ret1");
            
            if(ret2.equals("int")||ret2.equals("boolean")||ret2.equals("int[]"))
               police.throwType("unmatched type in neqExpression for ret2");
            
            //Both are non primitive
            //Check if the class is found in symbol table for both ret1 and ret2
            //if not then type error
            if(!T.findClass(ret1))
               police.throwType("in neqExpression::no class named "+ ret1);
            
            if(!T.findClass(ret2))
               police.throwType("in neqExpression::no class named "+ ret2);              
            
            //Both are present- check if ret1 is a superclass of ret2 or vice-versa
            if(!((T.checkAncestor(ret1,ret2))||(T.checkAncestor(ret2,ret1))))
               police.throwType("in neqExpression:: comparing unrelated types");

         }
         else
         {
            //Check if both the types are valid 
            if(ret1.equals("int")||ret1.equals("boolean")||ret1.equals("int[]"));
            else
            {
               //Check if non primitive is a member of symbol table T- if not, then 
               //its a type error(symbol not found only for undeclared vars)
               if(!T.findClass(ret1))
               police.throwType("in neqExpression::no class named "+ ret1);
            }
            
         }

         _ret = (R)"boolean";
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType("in plusExpression");
         }
         _ret = (R)("int");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType("in minusExpression");
         }
         _ret = (R)("int");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType("in timesExpression");
         }
         _ret = (R)("int");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int") || !ret2.equals("int"))
         {
            police.throwType("in divExpression");
         }
         _ret = (R)("int");
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String ret1 = "";
      String ret2 = "";
      ret1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ret2 = (String)n.f2.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int[]") && !ret2.equals("int"))
         {
            police.throwType("in arrayLookup");
         }
         _ret = (R)"int";
      }
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String ret1 = "";
      ret1 = (String)n.f0.accept(this, argu);
      if(((String)argu).equals("two"))
      {
         if(!ret1.equals("int[]"))
         {
            police.throwType("in ArrayLength");
         }
         _ret = (R)"int";
      }
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      String fargs = "";
      R cname = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      R fname = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      fargs = (String)n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      if(((String)argu).equals("two"))
      {
         
         StringTokenizer st = new StringTokenizer("");
         if(n.f4.present())
         {
            st = new StringTokenizer((String)fargs,",");
         }

         ArrayList<String> signature = new ArrayList<String>();
         while(st.hasMoreTokens())
         {
            signature.add(st.nextToken());
         }

         if(((String)cname).equals("this"))
         {
            //Method call within current scope-this is redundant now
            if(!T.verifySignature(T.curr_c.className, (String)fname, signature))
            {
               police.throwType("in messageSend, valid class not found");
            }
            _ret = (R)T.getReturnType(T.curr_c.className,(String)fname,signature);
         }
         else
         {
            //Arbitrary method call of another class
            //Get the class of the current object
            if(!T.findClass((String)cname))police.throwType("in messageSend class not found");
            if(!T.verifySignature((String)cname, (String)fname, signature))
            {
               police.throwType("in messageSend given method call is invalid");
            }
            _ret = (R)T.getReturnType(cname.toString(),(String)fname,signature);
         }

      }
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret = (R)"";
      String farg = (String)n.f0.accept(this, argu);
      if(((String)argu).equals("two")) 
      {
          if(n.f1.present())
          {
              for(int i=0;i<n.f1.size();++i)
              {
                  farg +=(String)n.f1.elementAt(i).accept(this, argu);
              }
          }  
          _ret = (R)farg;
      }
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=(R)"";
      String farg = (String)n.f0.accept(this, argu);
      farg = farg + (String)n.f1.accept(this, argu);
      if(((String)argu).equals("two"))_ret = (R)farg;
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=null;
      _ret = n.f0.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(n.f0.which==3)
         {
            //return the class of the given Identifier
            if(!T.findVariable((String)_ret))
            {
               police.throwType("in PrimaryExpression Class of "+ _ret.toString()); 
            }
            _ret = (R)T.getType((String)_ret);
         }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=(R)"int";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=(R)"boolean";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=(R)"boolean";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      _ret = (R)n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      _ret = (R)T.curr_c.className;
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      String chk = "";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      chk = (String)n.f3.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!chk.equals("int"))police.throwType("in ArrayAllocation");
         _ret = (R)"int[]";
      }
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      String class_name = "";
      n.f0.accept(this, argu);
      class_name = (String)n.f1.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!T.findClass(class_name)){
            police.throwSymbol("in AllocationExpression:: " + class_name);
         }
         _ret = (R)class_name;
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      String ret1= "";
      n.f0.accept(this, argu);
      ret1 = (String)n.f1.accept(this, argu);
      if(argu.toString().equals("two"))
      {
         if(!ret1.equals("boolean"))police.throwType("in NotExpression" + ret1);
         _ret = (R)ret1;
      }
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      if(argu.toString().equals("two"))_ret = n.f1.accept(this, argu);
      else n.f1.accept(this,argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public R visit(IdentifierList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(IdentifierRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

}
